[tool.poetry]
name = "netlint"
version = "0.1.0"
description = ""
authors = ["Leo Kirchner <leo@kirchne.red>"]

[tool.poetry.dependencies]
python = "^3.6"
ciscoconfparse = "^1.5.30"
click = "^7.1.2"
click-default-group = "^1.2.2"
Sphinx = { version = "^3.5.3", optional = true }
sphinx-rtd-theme = { version = "^0.5.2", optional = true }
m2r2 = {version = "^0.2.7", optional = true }

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
flake8 = "^3.9.0"
Sphinx = {version = "^3.5.3", extras = ["docs"]}
sphinx-rtd-theme = {version = "^0.5.2", extras = ["docs"]}
pytest = "^6.2.3"
coverage = "^5.5"
m2r2 = {version = "^0.2.7", extras = ["docs"]}

[tool.poetry.extras]
# The following section is required to install docs dependencies
# until RTD fully supports poetry: https://github.com/rtfd/readthedocs.org/issues/4912
docs = ["sphinx", "sphinx_rtd_theme", "m2r2"]

[tool.poetry.scripts]
netlint = 'netlint.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
