[tool.poetry]
name = "netlint"
version = "0.1.0"
description = ""
authors = ["Leo Kirchner <leo@kirchne.red>"]

[tool.poetry.dependencies]
python = "^3.8"
ciscoconfparse = "^1.5.30"
click = "^7.1.2"
click-default-group = "^1.2.2"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
flake8 = "^3.9.0"
Sphinx = {version = "^3.5.3", extras = ["docs"]}
sphinx-rtd-theme = {version = "^0.5.2", extras = ["docs"]}
sphinx-autodoc-annotation = {version = "^1.0-1", extras = ["docs"]}

[tool.poetry.scripts]
netlint = 'netlint.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
