[tool.poetry]
name = "netlint"
version = "0.1.0"
description = ""
authors = ["Leo Kirchner <leo@kirchne.red>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
ciscoconfparse = "^1.5.30"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
flake8 = "^3.9.0"
typer-cli = {version = "^0.0.11", extras = ["docs"]}

[tool.poetry.scripts]
netlint = 'netlint.main:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
